### ISSUE TITLE
jogging doesn't work with django 1.3

### ISSUE THREAD

**Issue by kmike** [zain/jogging#15]
The reason can be django's new LOGGING option (which has the same name as option used by jogging). 

```
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_manager(settings)
  File "/Users/kmike/envs/nadovmeste/src/django/django/core/management/__init__.py", line 438, in execute_manager
    utility.execute()
  File "/Users/kmike/envs/nadovmeste/src/django/django/core/management/__init__.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/kmike/envs/nadovmeste/src/django/django/core/management/base.py", line 191, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/kmike/envs/nadovmeste/src/django/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/Users/kmike/envs/nadovmeste/lib/python2.6/site-packages/south/management/commands/test.py", line 8, in handle
    super(Command, self).handle(*args, **kwargs)
  File "/Users/kmike/envs/nadovmeste/src/django/django/core/management/commands/test.py", line 37, in handle
    failures = test_runner.run_tests(test_labels)
  File "/Users/kmike/envs/nadovmeste/src/django/django/test/simple.py", line 361, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "/Users/kmike/envs/nadovmeste/src/django/django/test/simple.py", line 249, in build_suite
    app = get_app(label)
  File "/Users/kmike/envs/nadovmeste/src/django/django/db/models/loading.py", line 129, in get_app
    self._populate()
  File "/Users/kmike/envs/nadovmeste/src/django/django/db/models/loading.py", line 61, in _populate
    self.load_app(app_name, True)
  File "/Users/kmike/envs/nadovmeste/src/django/django/db/models/loading.py", line 78, in load_app
    models = import_module('.models', app_name)
  File "/Users/kmike/envs/nadovmeste/src/django/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/kmike/envs/nadovmeste/src/jogging/jogging/models.py", line 78, in <module>
    jogging_init()
  File "/Users/kmike/envs/nadovmeste/src/jogging/jogging/models.py", line 47, in jogging_init
    if 'level' in properties:
TypeError: argument of type 'int' is not iterable
```

**Comment by ianlewis** [comment]
I have a feeling Django 1.3 won't be supported in deference to the built in logging. Why would you want to use jogging with Django 1.3 anyway given it has logging that is very similar to jogging built in?
